# Name of the workflow
name: Telegram Bot Deployment

# Triggers for when the workflow should run
on:
  push:                # Run the workflow when code is pushed to the repository
    branches:
      - main           # On push to the main branch
  schedule:            # Or run the workflow periodically (e.g., every 6 hours)
    - cron: "0 */6 * * *"
  workflow_dispatch:   # Allows manual triggering of the workflow

# Define the jobs (tasks) in this workflow
jobs:
  deploy_bot:
    runs-on: ubuntu-latest    # The environment the job runs on (GitHub provides Ubuntu for free)

    steps:
    # Step 1: Check out the code from your repository
    - name: Checkout repository content
      uses: actions/checkout@v2

    # Step 2: Set up Python in the GitHub Action runner (Ubuntu machine)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'   # Specify Python version (adjust to your needs)

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Telegram bot script
    - name: Run the Telegram Bot
      run: |
        python bot.py

    # Step 5 (Optional): Keep the script running (if needed)
    - name: Keep bot running
      run: |
        nohup python bot.py &
